config/routes.rb
Rails.application.routes.draw do
    # devise_for :admins
    devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
    }

    resources :users do
        resources :songs, only: [ :index ], controller: :user_songs
    end

    namespace :user do
        resources :settings, only: [:index, :update]
    end

    resources :song_plays, only: [ :new, :create ]

    resources :progression_templates, except: [ :show, :index ]

    resources :progressions, except: [ :show, :index ]

    resources :scales, only: [ :index ]

    resources :songs do
      resources :progression_templates, only: [ :index ]
      resources :progressions, only: [ :index ]
      resources :user_favorites, only: [ :new ]
    end

    resources :song_filters, only: [ :create ]
    resources :song_searches, only: [ :create ]

    resources :progressions do
        resources :sequence_adjustments, only: [ :new ], controller: :progression_sequence_adjustments
    end

    resources :hints, only: [:index]

    resources :references, only: [:index]
    resource :references, only: [:index] do
        resources :chords, only: [:index]
    end
    resources :key_references, only: [:index]
    resources :progression_template_references, only: [:index]
    resources :progression_references, only: [:index]

    resources :instrument_views, only: [:create]

    resources :user_instruments

    resources :publications, only: [:index]

    resources :inquiries, only: [:index, :create]

    root "application#index"
end

app/controllers/references_controller.rb
# help pages menu
class ReferencesController < ApplicationController
    def index

    end

    def show

    end
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/views/references/index.html.erb
<%= tag.h1 t('content.references.page_title') %>
<%= tag.section class: "ctas" do %>
    <%= tag.h2 t('content.references.internal') %>
    <%= cta_with_description t('content.references.chord_composition'), references_chords_path, t('hints.chord_composition') %>
    <%= cta_with_description t('content.references.key_scale'), key_references_path, t('hints.key_scale') %>
    <%= cta_with_description t('content.references.progression_templates'), progression_template_references_path, t('hints.progression_templates') %>
    <%= cta_with_description t('content.references.progressions'), progression_references_path, t('hints.progressions') %>
    
    <%= tag.h2 t('content.references.external') %>
    <%= cta_with_description "musictheory.net", "https://www.musictheory.net", t('content.references.website_music_theory') %>
<% end %>